name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Test with the Go CLI
        run: make test
